### ISSUE TITLE
Add the license to a project.

### ISSUE THREAD

**Issue by Ebyrdeu** [fungover/thunder#12]
### Problem Description
Two other projects already have the MIT license. In light of this, wouldn't it be beneficial to also include a license for Thunder project

**Comment by kappsegla** [comment]
I removed the good first issue from the topic. Because some websites looks at github projects that are public and have issues marked with good first issue and lists these issues for other programmers to start with, often in open source projects. Maybe we can instead create our own tag with a similar name for the purpose of marking issues that can be good to start with as a first task?

**Comment by Ebyrdeu** [comment]
If this is how GitHub behaves, it would be better to create our own tag for this issue. The question is more about whether we should just implement that or also create a new issue to create a new tag.

**Comment by kappsegla** [comment]
> If this is how GitHub behaves, it would be better to create our own tag for this issue. The question is more about whether we should just implement that or also create a new issue to create a new tag.
It's not just github but also pages like https://goodfirstissue.dev/
Some more info here: https://www.freecodecamp.org/news/how-to-find-good-first-issues-on-github/

**Comment by Win-ther** [comment]
Created issue #19 to add our own Label to use instead of 'good first task'.

**Comment by kappsegla** [comment]
> Two other projects already have the MIT license. In light of this, wouldn't it be beneficial to also include a license for Thunder project

Sounds good with me to use MIT license. Here are some instructions how to add the license.
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Some help in choosing a license:
https://choosealicense.com/

Might have to check with any libraries and tools we are using. Do they have any restrictive licenses?
For this we can use the command `mvn project-info-reports:dependencies` which will generate a report under target/site with information about all our dependencies.
