### ISSUE TITLE
Handling connections requests

### ISSUE THREAD

**Issue by kappsegla** [fungover/thunder#16]
### Problem Description
When a new client connects #6 to serversocket we need to handle that connection and wait for a CONNECT request.
Broker should then return CONNACK message.

We need inputStream and outputStream from client socket and after reading some data we can check if the incoming request is a CONNECT request.
https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718028

`InputStream inputStream = socket.getInputStream();
 OutputStream outputStream = socket.getOutputStream();
 byte[] buffer = new byte[1024];

                int bytesRead = inputStream.read(buffer);
                if (bytesRead > 0 && buffer[0] == (byte) 0x10) {
                    System.out.println("Received MQTT CONNECT message from client");
                    byte[] connackMessage = new byte[]{(byte) 0x20, (byte) 0x02, (byte) 0x00, (byte) 0x00};
                    outputStream.write(connackMessage);
                    outputStream.flush();
                    System.out.println("Sent MQTT CONNACK message to client");`
                    
                  

- After a Network Connection is established by a Client to a Server, the first Packet sent from the Client to the Server MUST be a CONNECT Packet
- The Server MUST process a second CONNECT Packet sent from a Client as a protocol violation and disconnect the Client
- In a connect message the first byte is hexadecimal value 0x10

Response in form of CONNACK
https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718033

To prevent denial of service attacks against our server we could add a limit time and disconnect the client if inputStream.read(buffer); hasn't returned in for example 30 seconds.
Java supports timeout on sockets read using the [setSoTimeout method.](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/net/Socket.html#setSoTimeout(int))

**Comment by vonfredd** [comment]
> ### Problem Description
>In a **connect** message the first byte is hexadecimal value 0x20

I am confused about this. The first byte should be 0x20 in the **connack** message. Not the connect message, right?

**Comment by kappsegla** [comment]
> > ### Problem Description
> > In a **connect** message the first byte is hexadecimal value 0x20
> 
> The first byte should be 0x20 in the **connack** message. Not the connect message, right?

First byte in Connect should be 0x10 and first byte in ack is 0x20
