### ISSUE TITLE
Test Coverage for ClientHandler with Updated Code

### ISSUE THREAD

**Issue by yrlacornelia** [fungover/thunder#60]
### Problem Description
The existing test cases in the ClientHandlerTest are currently ineffective and in need of refinement.
With the recent updates to the code in the ClientHandler, there is no working test coverage for ClientHandler.  Therefore, it's imperative to enhance the test suite to ensure 80% coverage for the updated code

**Comment by hannastigland** [comment]
The tests needs to be extended with additional data because right now they establish a connection, but they also need to disconnect with the correct bytes for it to be accurate.

**Comment by Win-ther** [comment]
In our current main, the tests in ClientHandlerTest are working fine and gives well above 80% coverage for ClientHandler. It seems the tests stopped working in #46, and if that is the case shouldn't the tests be fixed in that same PR? Because as I understand it, this Issue cannot be fixed until breaking the tests by merging #46 with main.

**Comment by marcusju23** [comment]
> In our current main, the tests in ClientHandlerTest are working fine and gives well above 80% coverage for ClientHandler. It seems the tests stopped working in #46, and if that is the case shouldn't the tests be fixed in that same PR? Because as I understand it, this Issue cannot be fixed until breaking the tests by merging #46 with main.

I agree. It's crucial to maintain a high test coverage, and if the tests in ClientHandlerTest were working fine before #46, it makes sense to address any issues in that pull request itself. Ensuring that tests are not only functional but also consistent across code changes is essential for the overall stability of our codebase. I suggest we prioritize fixing the tests in #46 before merging it into the main branch to avoid any potential disruptions. This will not only resolve the current issue but also contribute to the long-term maintainability of our code. What are our thoughts on this approach?

**Comment by hannastigland** [comment]
Thanks for the input @Win-ther and @marcusju23, we are struggling with fixing the tests in our branch and thought making an issue would be a good solution. Since we all want this PR to be done for friday's release we will put some more time into it right now and try to solve the problem
